name: Development to QA branch merge the yml file.
on:
  push:
    branches: [ development,QA ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout the code
       uses: actions/checkout@v2
       
     - name: script file
       run: sh ./sh/ci.yml
       shell: pwsh
